# Generated by Django 3.2 on 2021-04-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('available_by', models.DateField()),
            ],
        ),
    ]
